### ISSUE TITLE
Remove dependency on EMW

### ISSUE THREAD

**Issue by docwilmot** [backdrop-contrib/paragraphs#1]
This uses a few calls to `entity_metadata_wrapper()` which needs removing and needs to update the controller to save revisions. Once this is done can remove dependency on EMW.

**Comment by docwilmot** [comment]
Removed the dependency, but this involved removing dependency on `Entity API` code as well, most important removed Entity property info getter and setter callbacks. I have no idea how much this will affect. Seems to work OK, but until we get some real world testing and/or automated tests, won't know for sure.

**Comment by daggerhart** [comment]
There are a number of calls to `entity_save()` in the module. From what I can tell, that function only exists within the entity_metadata_wrapper module.
https://github.com/backdrop-contrib/paragraphs/blob/1.x-1.x/ParagraphsItemEntity.inc#L429

**Comment by laryn** [comment]
Thanks @daggerhart!

@docwilmot do you have any thoughts on whether/how to proceed with solving this? See also:
https://forum.backdropcms.org/forum/how-does-one-create-paragraphs-field-programmatically

L.

**Comment by docwilmot** [comment]
The calls to `entity_save()` should be directly replaceable by ` $host_entity->save()` and `$entity->save()` respectively.

**Comment by laryn** [comment]
Hopefully going to be doing some Paragraphs clean-up and bug fixes in the next few days. @docwilmot can I pick your brain about the EMW/entity items mentioned above? Specifically:

 - Entity revision load: https://github.com/backdrop-contrib/paragraphs/issues/33
 - Entity wrapper issue: https://github.com/backdrop-contrib/paragraphs/issues/32
 - ParagraphsItemController->save() issue: https://github.com/backdrop-contrib/paragraphs/issues/31

As to `entity->save`, it looks like it's referenced in four places:

> .//ParagraphsItemEntity.inc:      return entity_save($this->hostEntityType, $host_entity);
> .//ParagraphsItemEntity.inc:      entity_save($this->hostEntityType, $this->hostEntity);
> .//plugins/panelizer/entity/PanelizerEntityParagraphsItem.class.php:  public function entity_save($entity) {
> .//plugins/panelizer/entity/PanelizerEntityParagraphsItem.class.php:    entity_save($this->entity_type, $entity);

Is Panelizer relevant in Backdrop or can/should that plugin be removed?

**Comment by docwilmot** [comment]
Hi there @laryn, I responded to the first two above. The third re saving entities would need a bit more time. Something to do with revisionKeys.
See previous comment re entity save.
And no Panelizer in Backdrop so far, so that could go I guess till someone ports it.

**Comment by laryn** [comment]
Closing this in light of https://github.com/backdrop-contrib/paragraphs/issues/48
