### ISSUE TITLE
View method issue

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/paragraphs#106]
From @herbdool in [another thread](https://github.com/backdrop/backdrop-issues/issues/1739#issuecomment-985737935):

> I noticed https://github.com/backdrop-contrib/paragraphs/blob/769e1db92419cfee145a80ee1e573c0f5a14cd00/ParagraphsItemEntity.inc#L570 which is calling a `view` method but it's not in core yet and it doesn't check that it's using `EntityPlusControllerInterface`. 
> 
> Maybe have it like https://github.com/backdrop-contrib/entity_plus/blob/489b908ea54ebefc1ce966971c6af09c5e51a0c6/entity_plus.module#L371.
> 
> Not sure what would happen otherwise, if/when we add this to core and if the parameters are different.

**Comment by laryn** [comment]
@herbdool This should do it, right? https://github.com/backdrop-contrib/paragraphs/pull/112

**Comment by herbdool** [comment]
@laryn I think so.

Then down the line you can decide whether to continue using entity_plus for this or use core.
