### ISSUE TITLE
Administrative Labels for Collapsible Paragraphs

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/paragraphs#135]
When paragraphs are collapsed on the node edit page, it's hard to tell them apart (in the same way that is used to be hard to tell custom content block on a layout). 

If there already some way to label them (admin labels)?

Which text block is which?

![image](https://user-images.githubusercontent.com/3144571/172337940-af4180f1-7628-46e9-9cf4-cd2a16768579.png)

**Comment by laryn** [comment]
Paragraphs creates a display mode for Paragraphs, called `Paragraphs Editor Preview`. You can add fields from that Paragraph type and adjust how they display in this "collapsed" preview.

**Comment by stpaultim** [comment]
@laryn - I'm experimenting with this now and don't see how to add a field to the collapsed view in edit mode. In fact, I'm not seeing that my changes to the "Paragraphs Editor Preview" display mode are having any effect at all.

I think I'm missing something.

**Comment by stpaultim** [comment]
@laryn - Nevermind. I figured it out. 

https://forum.backdropcms.org/forum/how-use-paragraphs-editor-preview

It seems this feature exists already and works great, once you figure it out. However, in my opinion, it's pretty darn difficult to figure out.
