### ISSUE TITLE
Issue with Block Reference fields

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/paragraphs#138]
I was trying to add a block reference field to a Paragraph Type and this is the result:

> Notice: Undefined property: ParagraphsItemEntity::$uid in paragraphs_item_access() (line 202 of /app/modules/contrib/paragraphs/paragraphs.module).

> TypeError: Argument 1 passed to paragraphs_paragraphs_item_access() must be an instance of ParagraphsItemEntity, string given, called in /app/core/includes/module.inc on line 975 in paragraphs_paragraphs_item_access() (line 231 of /app/modules/contrib/paragraphs/paragraphs.module).

**Comment by argiepiano** [comment]
Try using the dev version of Block Reference. There is a commit from Feb 5, 2019 that deals with parameters for access functions. The commit has not been released  (last release is from 2018). BTW, it looks like an abandoned project - one more to the list...

**Comment by argiepiano** [comment]
https://github.com/backdrop-contrib/blockreference/commit/2ea2a3407dc53607fe3657a0443940613c5b7e1c

**Comment by laryn** [comment]
I've opened an issue to check in with the maintainer: https://github.com/backdrop-contrib/blockreference/issues/13

**Comment by laryn** [comment]
This seems to be an issue with Block Reference so I'll close it here.
