### ISSUE TITLE
Feedback on Collapse Message

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/paragraphs#139]
I just got this feedback from a client. 

```
When I'm done editing a component, the buttons at the bottom just say: collapse, unpublish, remove. 
So I press collapse. Then I get this message: "This content must be saved to record recent changes" 
which made me think I needed to find a component-specific save button. I realized it just means I 
need to save the whole page at the bottom, but it boggled me for a sec.
```
Maybe the message should say - "Changes to this item will not be saved until the entire page is saved."

**Comment by laryn** [comment]
Or perhaps 'This page must be saved to record recent changes.'?

**Comment by olafgrabienski** [comment]
Maybe also of interest: the wording when something in a Layout has changed (before saving):

> This form has unsaved changes. Click "Save layout" to make changes permanent or "Cancel" to discard changes.

More words but also more clear, in my opinion.

**Comment by herbdool** [comment]
I did a variation of what @olafgrabienski mentioned: 

> Click "Save" at the page bottom to make changes permanent.

https://github.com/backdrop-contrib/paragraphs/pull/174

**Comment by laryn** [comment]
@herbdool I'd like to avoid using directional specifics (ie. "at the page bottom") since the button may not be in a particular location depending on a variety of factors. For example, Gin moves the Save button to the top of the page.

**Comment by herbdool** [comment]
@laryn how's this: I updated it to "Click the main "Save" button to make content changes permanent."

**Comment by laryn** [comment]
Thanks everyone -- merged.
