### ISSUE TITLE
Enable modal administration - Sometimes modal does not open fully

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/paragraphs#140]
I understand that this is an experimental feature. The only problem that we've been having with it is that sometimes (not always) the modal does not open fully.

![image](https://user-images.githubusercontent.com/3144571/180584126-9805bbff-d461-4602-9c07-d158e65aa019.png)

Usually, if we start scrolling on the page, the modal pops open and it's not a very big problem. But, in this specific test I did that work-a-round did not work. I had to close the modal and reopen it. Upon reopening, it opened correctly.

**Comment by argiepiano** [comment]
I experienced this same behavior with modals in other contexts (not opening correctly). I suspect it's a bug. I solved it by loading the js library backdrop.dialog.ajax in the page that contains the link that opens the dialog. As in adding `    backdrop_add_library('system', 'backdrop.dialog.ajax');` in a hook_preprocess_node()  hook.

The problem was that the needed library that controls the size of the modal was not being loaded correctly - you had to load it explicitly

**Comment by TeamTriplo** [comment]
I just tested adding  backdrop_add_library('system', 'backdrop.dialog.ajax'); in a hook_preprocess_node() hook and its working now. Now if anyone want to use in specific node they could easily get the node where want to put and make it working for specific node.

**Comment by argiepiano** [comment]
Ideally, as a potential fix for all situations, this library should be added within `paragraphs_field_formatter_view()` when the modal admin is enabled.

**Comment by laryn** [comment]
@argiepiano @stpaultim Would it make sense to add it here with these others using `#attached`?

https://github.com/backdrop-contrib/paragraphs/blob/1.x-1.x/paragraphs.module#L1839-L1844

**Comment by argiepiano** [comment]
Replacing `'backdrop.ajax'` with `'backdrop.dialog.ajax'` should  be enough in:
https://github.com/backdrop-contrib/paragraphs/blob/e1d39254e38cfccca5d323dda60293d485858154/paragraphs.module#L1844

Adding `'backdrop.dialog.ajax'` will automatically add `backdrop.ajax` 

But I have not tested whether this is the better location for this, or paragraphs_field_formatter_view

**Comment by laryn** [comment]
@stpaultim Are you willing to test the site that was having the issue with the change above?

**Comment by stpaultim** [comment]
We did get this working by hacking the module with some code based upon the suggestion by @argiepiano. I will ask my colleagues to chime in here with feedback on what worked for them and to test whatever patch we think will fix this problem. @laryn

**Comment by laryn** [comment]
Thanks @stpaultim -- if it works well, I think the cleanest would be to simply replacing 'backdrop.ajax' with 'backdrop.dialog.ajax' in the line discussed above. If that doesn't work well, let's try plan B (paragraphs_field_formatter_view).

**Comment by bdalomgir** [comment]
@stpaultim  I just replaced  'backdrop.ajax' with 'backdrop.dialog.ajax' in **paragraphs.module** at line 1844 and it's works for me. Thanks @argiepiano

**Comment by stpaultim** [comment]
@bdalomgir - Would you please create a PR for this module with that change? That will make it easier to discuss and test. 

Atten: @laryn and @argiepiano

**Comment by stpaultim** [comment]
@bdalomgir - Thanks for PR - https://github.com/backdrop-contrib/paragraphs/pull/142

**Comment by laryn** [comment]
Merged. Thanks @bdalomgir, @stpaultim, and @argiepiano!
