### ISSUE TITLE
Error: "Insert value list does not match column list"

### ISSUE THREAD

**Issue by robertgarrigos** [backdrop-contrib/paragraphs#148]
I'm having this error on a new site am working on:

```
EntityStorageException: SQLSTATE[21S01]: Insert value list does not match column list: 1136 Column count doesn't match value count at row 1 a NodeStorageController->save() (línia 510 de /app/www/core/modules/node/node.entity.inc).
```
When saving a node with a paragraph item which contains a date field with hours and minutes.

I tried the same paragraph date field WITHOUT hours and minutes, and it does NOT trigger the error. Also, the same date field WITH hours and minutes within the content type, not the paragraph, does NOT trigger the error either.

I have entity ui, entity reference, entity reference prepopulate, entity plus and entity tokens modules installed.

I tried with other older websites, on production, with paragraphs update and having the same problem. I cannot say this never happened before, though. I don't remember if I used date fields with time in paragraphs before.

Anyone with the same problem?

**Comment by argiepiano** [comment]
I've been able to reproduce this problem only when I use the HTML5 date widget. Not sure what's causing it, but I'll try to take a look.

**Comment by argiepiano** [comment]
OK, it's a bug in core, in `date_html5_element_validate()` specifically, which is supposed to take care of transforming the returned form values into something that can be stored in the date field table.  I'll open an issue there.

**Comment by argiepiano** [comment]
Issue https://github.com/backdrop/backdrop-issues/issues/5847

**Comment by robertgarrigos** [comment]
Confirmed in the PR https://github.com/backdrop/backdrop/pull/4248 that it fixed the problem. Thanks @argiepiano !

**Comment by laryn** [comment]
Closing as fixed in core -- thanks @argiepiano for the fix and @robertgarrigos for the report!
