### ISSUE TITLE
Add Paragraph Type Clone function

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-contrib/paragraphs#149]
As a site builder
I want to be able to clone a paragraph type
So that I can easily create a variant from the same field and display basis without having to recreate these manually.

I started off doing this [as a new module](https://github.com/backdrop-ops/contrib/issues/688) but realised that the best place to put the link would be in the drop menu, rather than having as a link on the page.  The module that inspired this was Content Type Clone and much methodology was derived from that but it is slightly different.  That module rebuilt the content type overview page which I don't think is ideal for paragraphs as it means any changes to that page need to be done in two places.

I realised it wouldn't take too much work to put as a function in Paragraphs and that it would make the user experience better.

So here is the question,  @laryn, should it be an enhancement (PR below) to Paragraphs or its own module?

Own module: https://github.com/yorkshire-pudding/paragraphs_type_clone
PR : https://github.com/backdrop-contrib/paragraphs/pull/150

**Comment by laryn** [comment]
@yorkshire-pudding This is great -- I think it is a valuable addition. Let me think on it a little as to whether it should be merged directly into Paragraphs. I'll also try to make some time to test the PR this week.

**Comment by yorkshire-pudding** [comment]
@laryn - any thoughts?

**Comment by laryn** [comment]
@yorkshire-pudding Sorry, I'm running behind on testing this. I still have it bookmarked at the top of my list.

**Comment by yorkshire-pudding** [comment]
@laryn - this PR and the separate module now clone permissions if they exist (i.e. if Paragraphs Type Permissions is enabled).

**Comment by laryn** [comment]
@yorkshire-pudding I've done some functional testing and it's looking good. I'm going to look through the code one more time this week.

**Comment by laryn** [comment]
Thanks for hanging in there on all those back-and-forths in the review @yorkshire-pudding -- merged! This will be a nice addition. And thank @argiepiano for looking things over with me.
