### ISSUE TITLE
Using the image library in a modal edit doesn't work

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/paragraphs#152]
When you select the image from the library and try to insert it, the modal closes completely without saving.

**Comment by olafgrabienski** [comment]
Confirmed (just stumbled upon it on a new site)! @laryn Do you already have plans (or an idea, how) to fix the issue?

**Comment by laryn** [comment]
@olafgrabienski I do have plans to fix it but haven't had any time to even start digging into it. I'm guessing it will require some Javascript. I'm also open to additional information being added here, or PRs, or ?? 😄

**Comment by laryn** [comment]
Further information:

- On an image field, the image library does not work. Once the image is selected the modal closes without sending the image back to the image field.
- On a rich text field, using the image library via the CKEditor button does work as expected.

The difference appears to be that CKEditor pops up a separate modal, so when that closes the original modal is still there. The image field doesn't open in a new modal, it reloads the library in the same initial modal, and when that closes there is nothing left.

**Comment by laryn** [comment]
This appears to be a core issue which now has a working PR -- closing this issue.
