### ISSUE TITLE
Modal buttons get confusing on nested multivalue paragraphs

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/paragraphs#153]
The individual paragraph item buttons (collapse, unpublish, etc.) all get anchored to the bottom of the modal and get very confusing on a modal edit of a nested multi-value paragraph.

![Image](https://user-images.githubusercontent.com/871421/215330515-6d781dab-4f2b-4978-af0e-0902ef369189.png)

**Comment by laryn** [comment]
WIP here https://github.com/backdrop-contrib/paragraphs/pull/154

![2023-01-31_00-04](https://user-images.githubusercontent.com/871421/215679409-37816303-e514-428f-99ef-dcf452af580f.png)

**Comment by laryn** [comment]
I think the linked PR is ready for review and testing if anyone is interested. Otherwise I'll probably test it on a few small personal sites before merging.

**Comment by yorkshire-pudding** [comment]
LGTM WFM 👍 
@laryn - I can confirm the bug and that the PR fixes this.  I may be a new convert to the modal admin side having never tried it before due to the experimental warning.

I've done a quick review of the code and it all makes sense to me.

**Comment by laryn** [comment]
Thanks @yorkshire-pudding! 

(Glad to have you trying out the modals! Issues like this one and https://github.com/backdrop-contrib/paragraphs/issues/152 are why it's still marked experimental)
