### ISSUE TITLE
Add Block feature does not display title of View block

### ISSUE THREAD

**Issue by mikesoltis** [backdrop-contrib/paragraphs#155]
I have a page displaying 2 Views blocks using the Layout and selecting "Default" for the block titles.

On the same page below the Layout blocks, I'm displaying the same 2 views using Paragraphs.

The blocks via the Layout show the Views titles while the Paragraphs rendering does not.  It appears to be a bug or a missing option.  The option is required to keep the title on this page in sync with the view.

I have not tested other kinds of Paragraph Blocks.

Thanks

![Screenshot 2023-02-23 at 17-49-48 BL4-2 Software Overview Macromolecular Crystallography](https://user-images.githubusercontent.com/78069725/221073723-9173eecd-bc0e-4bc7-8d02-f854e6f7f8a0.jpg)

**Comment by laryn** [comment]
Hi @mikesoltis! Is this using [the `blockreference` module](https://github.com/backdrop-contrib/blockreference) to add blocks within a Paragraphs field? If so, that is most likely the best place to add the feature request for an option to show the block title along with the block itself.

**Comment by laryn** [comment]
Actually, if that's what you're using there may already be an option for that in the blockreference field formatter:
 - https://github.com/backdrop-contrib/blockreference/blob/1a9684f7b915f07239feffe63bca01c4474e52eb/blockreference.field.inc#L60-L63

If you're using something different post a little more detail about how these blocks are added.

**Comment by mikesoltis** [comment]
Yes - thanks for the help.  I was able to set the display format "Title and Content" for the Paragraph type Block Reference in the Manage Display tab.
