### ISSUE TITLE
Remove paragraphs_bundle table

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/paragraphs#157]
No longer needed now that the bundles are stored in config.

**Comment by herbdool** [comment]
I've got a PR @laryn.

There already was a line to remove `paragraphs_bundle` but it kept the schema. So I removed that and had it check for existence of the table for those upgrading from d7.

**Comment by laryn** [comment]
@herbdool Thanks for catching this. Do we need to move that code to drop the table into a separate update hook at this point, to catch the folks who installed Paragraphs on Backdrop and got an empty schema implemented?

**Comment by herbdool** [comment]
@laryn I updated the PR. Added another update hook to drop the table if it exists.

**Comment by laryn** [comment]
Thanks @herbdool -- tested locally and code looks good. Merged!
