### ISSUE TITLE
Tokens in the the description of Paragraph reference fields do not get replaced

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/paragraphs#159]
According to the field UI, when you add a Paragraph reference field to a node, you can use a token in the description of the field.

<img width="677" alt="Screen Shot 2023-08-08 at 8 25 35 AM" src="https://github.com/backdrop-contrib/paragraphs/assets/9938978/05f5055e-3a05-4eb7-8326-28faf2a3c218">

However, those tokens are not replaced. The problem is in line 63 of `paragraphs_field_multiple_value_form()`, where the replacement should happen. PR coming.

<img width="468" alt="Screen Shot 2023-08-08 at 8 31 45 AM" src="https://github.com/backdrop-contrib/paragraphs/assets/9938978/c56f3f8e-fc92-4c82-a14a-d019bd59cd34">

**Comment by argiepiano** [comment]
PR #160. It takes the same approach as core. See https://github.com/backdrop/backdrop-issues/issues/6196

**Comment by laryn** [comment]
Merged. Thanks!
