### ISSUE TITLE
Issue with tokens?

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/paragraphs#16]
I'm not sure about this, but it shows up in my status report with a warning that says "Problems detected".

> The following token types are not defined but have tokens:

>>    $info['types']['paragraphs_item']

**Comment by herbdool** [comment]
There's only one mention of token in the paragraphs code and I don't think it's related to this. What are the steps for reproducing this error?

**Comment by laryn** [comment]
@herbdool I'm having trouble reproducing on a second server (but also having trouble solving the problem on the first server). I wonder if it's possibly related to https://github.com/backdrop-contrib/paragraphs/issues/11

I'll close this for now and reopen if needed and I figure out how to reproduce.

![screen shot 2018-09-25 at 1 22 38 pm](https://user-images.githubusercontent.com/871421/46035196-1ac65d80-c0c8-11e8-9f6b-6916c18ea313.jpg)

**Comment by olafgrabienski** [comment]
I'm currently testing the Paragraphs module, and I also see the above mentioned error on the Status report page.

So far, I've enabled the main module, added one paragraph bundle with three fields (text, youtube field, long text), configured its display and added the Paragraph field to a content type.

**Comment by olafgrabienski** [comment]
Update: I've reproduced the error, and this time I've tried to have a look at the *Status report* page after every step:

- enabled the main module: no error
- added a paragraph bundle: no error
- added two fields to the bundle (short text, youtube field): error

**Comment by laryn** [comment]
@olafgrabienski Thanks! I wonder if it could have to do with the Youtube field -- the site that I see this on has a Youtube field as well.

**Comment by olafgrabienski** [comment]
Interesting regarding the Youtube field! I can try to test it in another environment in the next days.

**Comment by olafgrabienski** [comment]
@laryn Yep, it seems to be *Youtube field*: In a new test, I've added three fields to a Paragraph bundle:

- Short text
- Long text
- Youtube field

The error didn't appear until I added the Youtube field.

**Comment by laryn** [comment]
@olafgrabienski If you get a chance to test https://github.com/laryn/youtube/commit/54d40e90329ebad95dd466fdacda563f86ec1b46 let me know.

**Comment by olafgrabienski** [comment]
@laryn Sure, I‘ll have a look in the next days.

**Comment by olafgrabienski** [comment]
@laryn Tested: I've patched a test site with https://github.com/laryn/youtube/commit/54d40e90329ebad95dd466fdacda563f86ec1b46, and the message in the *Status report* disappeared.

**Comment by laryn** [comment]
Fixed in the Youtube module.

**Comment by olafgrabienski** [comment]
For reference, here the link to the Youtube module issue: https://github.com/backdrop-contrib/youtube/issues/16
