### ISSUE TITLE
Field help text does not wrap but causes paragraph editor to expand to width of text

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-contrib/paragraphs#163]
**Steps to reproduce:**
1. Add a paragraph type with a field and add very long help text.  For example, I discovered this bug on Viewfield module (see text below), but reproduced on a plain short text field.
2. Edit a node with paragraphs on. The effect can be seen well if there are several other fields, especially ones with text editor
3. Add a paragraph of the type with long help text

_Text of ViewField:_

> A comma separated list of arguments to pass to the selected view. Enable the Token module to see a complete list of tokens that may be used as arguments. (Wrap arguments containing commas in double quotes and replace double quotes in arguments with a pair of double quotes.)

**Expected result:**
Text wraps and does not widen the paragraph editor dialog
![image](https://github.com/backdrop-contrib/paragraphs/assets/20357797/813b0275-90d8-4f4c-ac58-4d0faeeb6618)

**Actual result:**
Text does not wrap but widens the paragraph editor dialog for all 
![chrome_DOKpljgqnC](https://github.com/backdrop-contrib/paragraphs/assets/20357797/9fc59085-8fa6-4d58-ac21-aa47513552f8)

Note - this does not happen for the same help text on a field on the node create form.

**Comment by yorkshire-pudding** [comment]
@laryn - I've added a PR that fixes this but I don't know if this is the best fix or if there is something wider happening with the divs in the embedded editor that is different from the node edit form.

**Comment by laryn** [comment]
Thanks for your help tracking this down and verifying the wider issue, @yorkshire-pudding!

Closing this issue in favor of core issue: https://github.com/backdrop/backdrop-issues/issues/6365
