### ISSUE TITLE
Font size in nested paragraphs keep getting smaller and smaller when using Seven theme for editing

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/paragraphs#169]
When getting to a third level nesting, I started noticing that the font got smaller and smaller with each level:

![2024-03-07 20 46 11 bd3 lndo site 626367c5c3ad](https://github.com/backdrop-contrib/paragraphs/assets/1071483/c1b6776b-bff4-4968-841d-064560e6c262)

Seven assigns `font-size: 0.923em;` to the table element. If I change it to `font-size: 0.923rem;` then the font size for the second and third level nesting grows to match the first level.

This is probably an issue for core, but it's unlikely to affect many modules other than paragraphs. So maybe a quick fix could be implemented here. Or at least confirm the bug and plausible fix.

According to https://www.digitalocean.com/community/tutorials/css-rem-vs-em-units:
> em units for the font-size property will be relative to the font-size of the parent element. em units on other properties than font-size will be relative to the font-size of the current element. rem units sizes will always be relative to the font-size of the root html element.

**Comment by herbdool** [comment]
@laryn I've added a PR.

**Comment by laryn** [comment]
@herbdool Merged. It does seem to be a Seven issue and I would prefer to avoid theme-specific fixes but I also know that changing CSS for core is a nightmare and this is a core theme available out of the box, so it would be good to have it working...

**Comment by herbdool** [comment]
@laryn I'm trying to recall this line:

```
  .paragraphs-item {
      white-space: normal;
    }
```

Because I'm not sure if it's working. Is it there to override this from core:

```
tr.odd .form-item, tr.even .form-item {
    margin-top: 0;
    margin-bottom: 0;
    white-space: nowrap;
}
```

It doesn't seem to be working.

**Comment by olafgrabienski** [comment]
> I'm trying to recall this line (...)

@herb There is a similar line in https://github.com/backdrop-contrib/paragraphs/pull/171/files. Maybe two ways to fix the same issue with preview text?

Note: I'm interested in the _white-space_ question re Paragraphs, because I recently had to add the following fix to a site which uses Paragraphs, after upgrading the site to CKEditor 5. Without that fix, when editing text in long text fields, it doesn't break into several lines. Not sure if this was already mentioned somewhere.

```
.ck-content {
  white-space: normal;
}
```

**Comment by herb** [comment]
@olafgrabienski you mean @herbdool i believe

**Comment by olafgrabienski** [comment]
Oh yes, you're right. Sorry for the noise.
