### ISSUE TITLE
Paragraphs preview doesn't wrap the text

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/paragraphs#170]
Previewing text in the paragraphs widget looks like:

![2024-03-14 16 38 35 bd3 lndo site 54eddf296c8c](https://github.com/backdrop-contrib/paragraphs/assets/1071483/4c72ec74-981a-407d-90ff-c80be59145d2)

`system.theme.css` assigns `nowrap` to `<tr>`.

**Comment by herbdool** [comment]
@laryn I've got a PR.

**Comment by laryn** [comment]
Related to https://github.com/backdrop/backdrop-issues/issues/6364

And the follow up that would fix it more globally seems to have stalled out as many CSS related issues do: 
https://github.com/backdrop/backdrop-issues/issues/6365

So I've merged this in here. Thanks @herbdool.
