### ISSUE TITLE
Closed and Preview edit mode vs. FAQ Field's Formattable textarea

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-contrib/paragraphs#182]
I've discovered a conflict between two of the _Paragraphs_ 'Default edit modes' and a particular 'Answer widget' of the _FAQ Field_ module. Not being sure if it's a Paragraphs or a FAQ Field issue, I'm gonna report the issue not only in the [FAQ Field queue](https://github.com/backdrop-contrib/faqfield/issues/5) but also here.

I'm trying to use a FAQ Field in Paragraphs. In the field configuration I've set the Answer widget to "Formattable textarea". This works fine at first sight, I can create a FAQ section. However, when I edit the FAQs again, the content in the edit form seems to be removed. Instead of my content, I see the term "Array" in the editor (see screenshot below).

In the DBlog, I see the following notice:

> Array to string conversion in check_plain() (line 2089 of my-path-to/core/includes/bootstrap.inc).

There is no issue when I change the 'Default edit mode' of Paragraphs to "Open". The same is true when I change the FAQ Field answer widget to "Textarea". So, there seems to be a conflict between the FAQ Field "Formattable textarea" and the 'Default edit modes' "Closed" and "Preview" from Paragraphs.

---

**Answer widget is Formattable textarea: "Array" instead of content**.  The issue occurs in the moment when I open the Closed (or Preview) edit mode to edit the FAQs.
<img src="https://github.com/backdrop-contrib/faqfield/assets/14188307/be300308-724b-4395-bae2-0bc52647bd56" width="600">

**Answer widget is Textarea** or **Default edit mode is Open**: content as expected
<img src="https://github.com/backdrop-contrib/faqfield/assets/14188307/d6eeae0e-6430-48f0-a747-6159166ba912" width="600">

**Comment by laryn** [comment]
I believe this is an FAQ Field issue, so I'll close for now. See: https://github.com/backdrop-contrib/faqfield/issues/5#issuecomment-2292760478
