### ISSUE TITLE
Can theme preprocess hooks work for paragraphs_item types/bundles?

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-contrib/paragraphs#194]
While I see that `THEMENAME_preprocess_paragraphs_item()` is recognised and invoked, I thought, that `THEMENAME_preprocess_paragraphs_item__BUNDLEMACHINENAME()` might also work assuming that a template existed in the theme called `paragraphs-item--BUNDLEMACHINENAME.tpl.php` but I can't seem to get it to work. Am I doing something wrong or is this not possible?

**Comment by argiepiano** [comment]
You can see in `template_preprocess_paragraphs_items()` that the theme suggestion for BUNDLENAME is not provided, thus the template won't be used. You can create a preprocess function in your theme to add the bundlename option.

 EDIT: you are talking about `paragraphs_item` or `paragraphs_items`?

**Comment by argiepiano** [comment]
~~Notice in your message you wrote `paragraphs-item--BUNDLEMACHINENAME.tpl.php`  (plural on paragraphs, which won't work)~~

Just ignore me haha. I'm not sure what I'm doing today

**Comment by yorkshire-pudding** [comment]
> You can see in `template_preprocess_paragraphs_items()` that the theme suggestion for BUNDLENAME is not provided, thus the template won't be used. You can create a preprocess function in your theme to add the bundlename option.
> 
> EDIT: you are talking about `paragraphs_item` or `paragraphs_items`?

Yes, I am using `paragraphs_item`. The template is being picked up, but I can't see similarly named preprocess functions working
![image](https://github.com/user-attachments/assets/4237a546-3e6d-41da-ab44-738e8fa749f9)

I can work around it if is not intended to work, but just wanted to see if it is possible.

**Comment by argiepiano** [comment]
I think there may be a syntax error in the suggestions for paragraphs-item. I see these lines in `template_preprocess_paragraphs_item`

```php
// Add suggestions.
  $variables['theme_hook_suggestions'][] = $paragraphs_item_type;
  $variables['theme_hook_suggestions'][] = $paragraphs_item_type . '__' . $bundle;
  $variables['theme_hook_suggestions'][] = $paragraphs_item_type . '__' . $bundle . '__' . $variables['view_mode'];
  $variables['theme_hook_suggestions'][] = $paragraphs_item_type . '__' . $paragraphs_item_id;
```

This is missing the name of the hook. I believe the correct suggestions should be:

```php
// Add suggestions.
  $variables['theme_hook_suggestions'][] = 'paragraphs_item__' . $paragraphs_item_type;
  $variables['theme_hook_suggestions'][] = 'paragraphs_item__' . $paragraphs_item_type . '__' . $bundle;
  $variables['theme_hook_suggestions'][] = 'paragraphs_item__' . $paragraphs_item_type . '__' . $bundle . '__' . $variables['view_mode'];
  $variables['theme_hook_suggestions'][] = 'paragraphs_item__' . $paragraphs_item_type . '__' . $paragraphs_item_id;
```

Try that and see what happens.

**Comment by yorkshire-pudding** [comment]
I'm a bit confused.
`THEMENAME_preprocess_paragraphs_item__paragraphs_item__header()` doesn't seem right.
I did dpm to see what those variables were.

**Comment by argiepiano** [comment]
Huh? My suggestion was to modify those lines I pasted above in  `template_preprocess_paragraphs_item`. Those suggestions seem wrong as they are - I think that's a bug.

**Comment by argiepiano** [comment]
OK, I think I probably misread your OP. So, your problem is not that your template suggestion is not working, but rather, that your preprocess function is not being called? AFAIK the preprocess functions do not use the pattern `THEMENAME_preprocess_paragraphs_item__BUNDLEMACHINENAME`. They only work as `THEMENAME_preprocess_paragraphs_item` and you have to do a conditional to check the bundle name inside the implementation.

**Comment by yorkshire-pudding** [comment]
Thanks @argiepiano - I'll do that.  I wanted to check I wasn't missing something, but I can work with that approach.

**Comment by laryn** [comment]
@yorkshire-pudding I haven't delved into that in terms of whether it's possible (I believe you that it's not working currently), but I'm not opposed to `THEMENAME_preprocess_paragraphs_item__BUNDLEMACHINENAME` functionality if you figure out what's needed and it's not intrusive to add/fix.
