### ISSUE TITLE
Error when trying to remove Paragraph

### ISSUE THREAD

**Issue by davegmk** [backdrop-contrib/paragraphs#2]
Many thanks for your work on getting Paragraphs into Backdrop.

I've been testing on Backdrop 1.10.1.  I get a fatal error when trying to remove a Paragraph from a node using the 'Remove' button.

The Paragraph is removed as expected but when the node is saved I get a ' The website encountered an unexpected error. Please try again later' message.

In the logs I have the following error:

Error: Call to undefined method ParagraphsItemEntity::isDefaultRevision() in ParagraphsItemEntity->deleteRevision() (line 464 of /home/insite/webapps/backdrop/modules/paragraphs-1.x-1.x/ParagraphsItemEntity.inc).

Cheers

**Comment by docwilmot** [comment]
Thanks for the review. Please try again, may have fixed it.

**Comment by davegmk** [comment]
Many thanks, removal now seems to be working.
