### ISSUE TITLE
Remove unneeded TODO

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/paragraphs#22]
In paragraphs.module there's:

```
// TODO This variable was probably removed in Backdrop without replacement.
  state_set('menu_rebuild_needed', TRUE);
```

We don't need the TODO since in fact the variable *is* now a state https://api.backdropcms.org/change-records/converted-all-variables-cmi. The code is correct.

**Comment by laryn** [comment]
Thanks @herbdool !
