### ISSUE TITLE
cannot install this module with drush

### ISSUE THREAD

**Issue by robertgarrigos** [backdrop-contrib/paragraphs#24]
I couldn't install this module with lando and drush. Got this error message:

```
Error: There is no release located at https://github.com/backdrop-contrib/paragraphs/releases/download//paragraphs.zip.
	Try visiting the paragraphs page directly: https://github.com/backdrop-contrib/paragraphs
```

I could install other modules using this method, but not this module. Bakcdrop 1.11.2. Lando v3.0.0-beta.47

**Comment by laryn** [comment]
@robertgarrigos Strange! I'll take a look. Hopefully I'll be able to make a new release in not too long, which may be a good way to test if the release shows up as expected for Drush. (Any chance you can help me test https://github.com/backdrop-contrib/paragraphs/issues/23?)

**Comment by guidot** [comment]
I just did a successful `drush dl paragraphs` (1.x-1.0.1). So I guess this is no longer an issue.
