### ISSUE TITLE
Field group on paragraph display doesn't show up

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-contrib/paragraphs#26]
I've added a *Field group* to the Default display of a Paragraph bundle but the *Field group* doesn't show up on the content item with the corresponding Paragraph field.

So far, I've tried to display a Div and a Fieldset group, and both don't show up, irrespective of the group's setting "collapsed" vs. "collapsible".

I'm new to Paragraphs with Backdrop, so I might have missed something. I'd appreciate if someone could try to reproduce the issue.

**Comment by laryn** [comment]
Thanks @olafgrabienski -- I'll try to take a look at this at some point relatively soon but please update if you have any further information as you test.

**Comment by laryn** [comment]
@olafgrabienski I added a Field Group to a test paragraph bundle and put a few dummy fields inside it. When I add the paragraph bundle to a content type, I can add a paragraph to the new content page and it has a collapsible fieldset around it:

![screen shot 2019-02-19 at 5 00 33 pm](https://user-images.githubusercontent.com/871421/53053808-08c6cc00-3468-11e9-8f4d-9a7123fc86be.jpg)

I tried with a `Div` and it also seems to work, albiet without a visual border:

![screen shot 2019-02-19 at 5 04 05 pm](https://user-images.githubusercontent.com/871421/53053923-66f3af00-3468-11e9-81bc-17798e742a53.jpg)

Can you provide more feedback on how to reproduce, or what you are doing differently?

**Comment by laryn** [comment]
@olafgrabienski Oh, my bad. You're doing this in the display settings, not the field settings. I can reproduce and will try to think through how to tackle this...

**Comment by olafgrabienski** [comment]
> You're doing this in the display settings, not the field settings.

Yes, I should have said that more clearly, good that you figured it out!

**Comment by laryn** [comment]
@olafgrabienski Another one that is solved by the `entityplus` branch, I think. Can you verify? That branch adds a dependency on "Entity Plus" and ends up solving a bunch of these issues.

**Comment by olafgrabienski** [comment]
@laryn Thanks for coming back to this issue! I'm on a vacation currently, will test the fix when I'm back home.

**Comment by olafgrabienski** [comment]
Coming back late to this, sorry! I've tested the current Paragraphs `1.x-1.x` branch (hoping it's the right one - on module page it says, requires Entity Plus) together with Entity Plus 1.x-1.0.5. Strange enough, it doesn't seem to work so far. Here's what I've done:

- Added a Paragraph type with three fields: Title, Youtube-Video, Description
- On Paragraph Display (both Default and Full): Added a Field group (Fieldset, later Div), and put the Description inside of the Field group
- Checked *Manage display > Paragraph Items* on the content type in question. View mode is "Full content" (Default not available)
- Had a look at a node display of my content type: no field group (even after clearing caches)

Did I miss something?

**Comment by laryn** [comment]
@olafgrabienski No, just tested again and it's not working. Reopened.

**Comment by kelizoliva** [comment]
They mentioned over in the field group thread (which I am sure you saw) that it looks like something at the template level, I am assuming meaning that `paragraphs-item.tpl.php` is not rendering an array of fields for field group to wrap individually.

**Comment by laryn** [comment]
> On template level of Paragraphs we can see $content variable contain already rendered HTML string instead of array of content items (e.g. fields). This make separate fields not templatable at all. But it is issue of Paragraphs module, not Field Groups IMHO.

**Comment by laryn** [comment]
@olafgrabienski I think @argiepiano 's work in https://github.com/backdrop-contrib/paragraphs/issues/113 solves this issue as well. Please test to be sure and reopen if it doesn't work for you (it works in my testing).

**Comment by argiepiano** [comment]
I haven't tested the fix with Field Group, so, @olafgrabienski , if you see any issues let us know.

**Comment by olafgrabienski** [comment]
Hey @laryn and @argiepiano, I've finally tested the fix with Field Group, and it's working perfectly. Thank you very much!

(Tested with Paragraphs 1.x-1.2.0-alpha2 and Field Group 1.x-1.1.0.)
