### ISSUE TITLE
Undefined index error for #type on remove_button markup item

### ISSUE THREAD

**Issue by bradbulger** [backdrop-contrib/paragraphs#29]
I have a Paragraphs field set to use buttons, with no default values so it starts out with no paragraphs. When I am looking at the node creation form, if I click on the Add Paragraph button, and then the Remove button, I get an error:

> Notice: Undefined index: #type in form_process_actions() (line 3369 of /mypath/www/core/includes/form.inc).

It's complaining about the 'remove_button' item that's just #markup value. If you add '#type' as "markup", the error goes away.

**Comment by laryn** [comment]
@bradbulger Interesting. According to the docs, we don't need it but according to your experience we do. 😄 

https://api.backdropcms.org/form_api#markup
> Note that there is no need to declare a form element as #type = 'markup', as this is the default type.

I'll ask quickly on Gitter to see if this is something that needs to be fixed in core, otherwise I'll merge here. 
Thanks!

**Comment by laryn** [comment]
@bradbulger Do you want to make a PR against core for this one? 
https://github.com/backdrop/backdrop-issues/issues/3512

We could do this to "fix" it here but then someone else would see it again later. I think all it needs is a `isset($element[$key]['#type'])` in the beginning of the `if` statement in this spot:
https://github.com/backdrop/backdrop/blob/1.x/core/includes/form.inc#L3367-L3369

**Comment by bradbulger** [comment]
I don't have an opinion about it. We can either adjust paragraphs to meet the expectations of core, or adjust core to check its expectations. It's an edge case, I think, related to reusing the name "remove_button" that was previously a submit button.

**Comment by bradbulger** [comment]
Or, no, I misspeak - it's that form_process_actions() assumes that all the items in an "actions" container are actual form elements. The name of the markup item is irrelevant. So yeah, I think you're right. I'll add a PR on 3512.

**Comment by laryn** [comment]
Fixed in core.
