### ISSUE TITLE
"You are not allowed to add any of the bundles."

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/paragraphs#3]
I'm having trouble giving access to an editor to be able to add/edit bundles. I've tried with and without the permissions sub-module (and the related permissions that it creates), and have also tried granting "Administer paragraphs bundles" as a test (although I'd prefer not to do this on the live site), but this is the persistent message:

> You are not allowed to add any of the bundles.

**Comment by laryn** [comment]
Maybe related? 
https://github.com/backdrop/backdrop-issues/issues/3011

**Comment by klonos** [comment]
Not sure when exactly this port was made (off of which version of the respective d.org module I mean) and if is been kept up to date with recent fixes, but these tickets from the d.org module could be related:

[Paragraphs bundle access breaks on draft revisions](https://www.drupal.org/project/paragraphs/issues/2562875)
[Bundles are disabled when parent entity has no access callback defined](https://www.drupal.org/project/paragraphs/issues/2724551)

**Comment by docwilmot** [comment]
Thanks for the review. Please try again, may have fixed it.
@laryn this shouldnt be a problem; I integrated the `entity_access()` calls into the module directly.
@klonos those issues are not likely related. (Although they probably still exist for nested paragraphs since I dont see a merged patch fix).

**Comment by laryn** [comment]
Yes, seems to solve it -- thanks!
