### ISSUE TITLE
Scheduled publication doesn't work with paragraphs

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/paragraphs#33]
Cron gave this error when trying to publish a node that has paragraphs:

> Error: Call to undefined function entity_revision_load() in paragraphs_item_revision_load() (line 60 of /path/modules/paragraphs/paragraphs.module).

**Comment by docwilmot** [comment]
To get rid of the error we could just copy and rename `entity_revision_load()` from D7 Entity API, as it looks simple. But dont know if that would fix scheduled publication. Worth a try.

**Comment by laryn** [comment]
While generally not a fan of just duplicating functions in potentially a bunch of different modules/places, this is a pretty small function. I left a note so that [if `entity_revision_load` gets into core](https://github.com/backdrop/backdrop-issues/issues/3777) or if I add a future dependency on Entity Plus, I can be reminded to revert this. (And some of the other `entity_revision_` functions that were already duplicated)

Thanks!
