### ISSUE TITLE
Hiding and rendering content in .tpl

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/paragraphs#37]
[From the Backdrop Forum](https://forum.backdropcms.org/forum/error-rendering-fields-paragraphs-item-bundlenametplphp):

> I'm trying to render fields in paragraphs-item--bundlename.tpl.php like it's shown in the description:

`<?php print render($content['field_example']); ?>`

> When I go and check it in the frontend, then I see the "site under maintenance" message. Only for the link I was trying if it is working. 

> Is it a bug or am I doing something wrong?

**Comment by laryn** [comment]
**MartinL** have you ever done this successfully in the Drupal 7 version? I am just doing some testing and I am not having success there. I am trying to narrow down if this is a porting-to-Backdrop issue or a module issue that was inherited from D7.

In fact, I can't get any changes in the `paragraphs-item.tpl.php` to get picked up at all in Drupal 7. I think [this is where we at least got that far in Backdrop](https://github.com/backdrop-contrib/paragraphs/issues/7). Now we may need to figure out why the `render`/`hide` functions aren't working as expected in the tpl...

**Comment by herbdool** [comment]
It worked for me in Drupal 7. I haven't tried in Backdrop but that template should be there in the module itself. And you can turn on theme debug to check which templates are suggested.

**Comment by laryn** [comment]
Cross-posted in the forum:

> @MartinL -- are you up for doing some testing?
> You'll need:
> - install and activate the `Entity Plus` module, [including the changes from this PR](https://github.com/backdrop-contrib/entity_plus/pull/18).
> - the [`entityplus` branch of Paragraphs](https://github.com/backdrop-contrib/paragraphs/tree/entityplus) (this has a dependency on Entity Plus)
> Let me know if that solves it for you. Testing looks good on my end.
