### ISSUE TITLE
Review `entity_revision_` functions

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/paragraphs#38]
In https://github.com/backdrop-contrib/paragraphs/issues/33 I (maybe temporarily) duplicated the `entity_revision_load()` function but am now seeing that we have other `entity_revision_` function calls, and there was already some other duplication of `entity_revision_` functions during the port. 

It would be good to review and determine if there are any loose ends here, and whether we can move forward for now with the duplicated functions or whether we should consider a dependency on `Entity Plus` to provide these functions, or wait to see [if they get in core](https://github.com/backdrop/backdrop-issues/issues/3777).

See also (a more thorough code review is likely necessary):

 - https://github.com/backdrop-contrib/paragraphs/blob/1.x-1.x/ParagraphsItemEntity.inc#L314
 - https://github.com/backdrop-contrib/paragraphs/blob/1.x-1.x/ParagraphsItemEntity.inc#L417

**Comment by bradbulger** [comment]
By a dependency on Entity Plus, you mean like calling entity_plus_save() instead of the missing entity_save(), for instance?

**Comment by laryn** [comment]
@bradbulger Yes, exactly, Requiring the `entity_plus` module and then adjusting all the function calls that previously existed in Drupal to the `entity_api` module (and which don't exist in Backdrop core) to use the `entity_plus` version.

I think that's how I lean but am hoping for more feedback from others.

Doing this might mean undoing some of https://github.com/backdrop-contrib/paragraphs/issues/1#issuecomment-396658610

**Comment by bradbulger** [comment]
I'd lean towards putting the Entity API into core. I'm always surprised that it isn't.

**Comment by laryn** [comment]
@bradbulger Most of it is, but there are some parts that are not. I'm not sure exactly how that line was drawn.

Related core conversations: 

- https://github.com/backdrop/backdrop-issues/issues/49
- https://github.com/backdrop/backdrop-issues/issues/1649
- https://github.com/backdrop/backdrop-issues/issues/3777

**Comment by laryn** [comment]
Note: I just tried to use the "Promote" action on the content overview page and got:

> Error: Call to undefined function entity_revision_load() in paragraphs_item_revision_load() (line 60 of /path/modules/paragraphs/paragraphs.module).

**Comment by sternhagel** [comment]
I'm trying to get Paragraphs working with Feeds, and I'm getting the following error message:

> Error: Call to undefined function entity_revision_set_default() in ParagraphsItemEntity->save() (line 417 of [...]/modules/paragraphs/ParagraphsItemEntity.inc).

This function doesn't seem to be defined anywhere, not in core "Entity" module, and not in contrib "Entity Plus" module. So I'm afraid requiring the "Entity Plus" module wouldn't fix this particular issue.

**Comment by laryn** [comment]
@sternhagel That would need to be renamed to [`entity_plus_revision_set_default`](https://github.com/backdrop-contrib/entity_plus/blob/1.x/entity_plus.module#L613-L619) if we make Entity Plus a dependency. (The Entity Plus module changed the function names to avoid conflicts if they ever were put into core afterwards)

**Comment by laryn** [comment]
@sternhagel I made a new branch for testing, which adds a dependency on Entity Plus (although it requires this PR on Entity Plus: https://github.com/backdrop-contrib/entity_plus/pull/16/files). Revisions with Paragraph fields are working for me using this branch. Care to test?

https://github.com/backdrop-contrib/paragraphs/compare/entityplus

If Entity Revision functions get into core we may not need to keep the Entity Plus dependency, but will need to test obviously.

**Comment by sternhagel** [comment]
@laryn Thanks for fixing this!

I tested your new branch and it seems to work just fine. Saving new revisions with Paragraphs fields works, and reverting to an older revision works as well.

However, there are some error notices I didn't see before.

On viewing a node with a paragraph:

> Warning: Theme hook "entity" not found.

^^^ might be related to following issue: https://github.com/backdrop-contrib/paragraphs/issues/43

and on reverting to a different revision:

> Notice: Undefined property: ParagraphsItemEntity::$original in file_field_update() (line 267 in [...]/core/modules/file/file.field.inc).

**Comment by laryn** [comment]
@sternhagel Does the new branch work with Feeds as described in https://github.com/backdrop-contrib/paragraphs/issues/38#issuecomment-560425201 ?

**Comment by laryn** [comment]
@sternhagel Can you test again with the latest commits on the `entityplus` branch, as well as this PR in the `Entity Plus` module itself?
https://github.com/backdrop-contrib/entity_plus/pull/18

**Comment by sternhagel** [comment]
@laryn Thanks very much, with the latest commits (and the PR in "Entity Plus") the `entityplus` branch works with Feeds and the "Paragraphs Mapper" module.

There are still some warnings and errors filling up the error log though - but they're not generated by the "Paragraphs" module, so I think I shouldn't post them here.

**Comment by bradbulger** [comment]
I'm getting a fatal error updating a node with a multivalue paragraphs field, where it is trying to insert a row into paragraphs_item_revision with the existing item's current revision_id (and so an integrity constraint violation). Could that be related to this issue?

**Comment by PepeMty** [comment]
> Note: I just tried to use the "Promote" action on the content overview page and got:
> 
> > Error: Call to undefined function entity_revision_load() in paragraphs_item_revision_load() (line 60 of /path/modules/paragraphs/paragraphs.module).

Hey there. 
I just updated my core from BD 1.13.5 to 1.14.0 and got this exact error.
Any advice on this issue...?

**Comment by laryn** [comment]
@sternhagel @bradbulger @PepeMty I just took over maintenance of the Entity Plus module and am going to make a dependency on it from Paragraphs. Please install or update your Entity Plus to the latest version (just released) and **while using the `entityplus` branch of Paragraphs** please test. Would appreciate report back as to whether everything looks good. If so I'll make a new Paragraphs release with the Entity Plus dependency.

**Comment by bradbulger** [comment]
That's the combination I tried for #31 and saving the node with the content type set to create new revisions by default worked. I'll restore that setup and try out some other actions.

**Comment by PepeMty** [comment]
@laryn 
Wow...! Seems that that did the trick.
Need to make a more thorough checkout, but I don't have any more error messages.
Thanks again.
Jose

**Comment by sternhagel** [comment]
@laryn That's great! I've tested the new version, and I can't reproduce any errors related to this module.
I'll do more testing and post any issues here...
