### ISSUE TITLE
Focus jumps to node title

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/paragraphs#4]
When adding a new paragraph, focus keeps jumping back to the node title which is a usability problem.

**Comment by docwilmot** [comment]
I'm not seeing this. Might need more info.

**Comment by laryn** [comment]
Hmm.. Maybe something in my installation somehow? I'll do further testing.

**Comment by laryn** [comment]
Okay, it seems to be because that's where the focus was when I clicked the button to add the paragraph. (I just went right to testing the paragraph functionality without adding any other info to the node) It was so noticeable in this case because the field list is long and the paragraph field was below the scroll, and so it jumped all the way back to the top and I had to scroll down again to see the paragraph I just added. If I click into a field that is closer to the paragraph before adding the paragraph button it keeps focus in that other field and doesn't make me scroll.

I'm not sure how big of an issue this actually is in general. I'll let you decide if there's anything to be done or if not, close this issue.

**Comment by olafgrabienski** [comment]
@laryn I've seen the same behaviour (focus 'jumps' to node title input). It happens usually with the node title because the title input has focus by default. Some further observations:

- When I put the cursor out of the title input before adding a paragraph, the focus doesn't jump back.
- But when I place the cursor in *another* field input, e.g. the *Body* textarea, before adding a paragraph, the focus jumps to *that* input.

**Comment by laryn** [comment]
@olafgrabienski Perhaps there is some little javascript we can add in to give focus to the paragraph button that is clicked. I think that would prevent this type of jumping around.

**Comment by olafgrabienski** [comment]
> Perhaps there is some little javascript we can add in to give focus to the paragraph button that is clicked.

Sorry for the late feedback. Unfortunately, I've not enough JavaScript skills. FYI, here's the core issue which introduced the focus of the node title input: https://github.com/backdrop/backdrop-issues/issues/2625, maybe there's useful information to resort to when changing the behavior of Paragraphs.

**Comment by laryn** [comment]
Thanks @olafgrabienski -- that is useful information and I'll try to see if I can relate something from that thread to this module. e.g. maybe similar to [what was done in that issue](https://github.com/backdrop/backdrop/pull/1832/files), so an "autofocus" on the paragraph form items so when they are added, they get focus.

**Comment by laryn** [comment]
Tracking core issue: https://github.com/backdrop/backdrop-issues/issues/5266

**Comment by laryn** [comment]
As https://github.com/backdrop/backdrop-issues/issues/5386 was merged I think this issue can probably be closed here.
