### ISSUE TITLE
Error when translating nodes with nested paragraphs

### ISSUE THREAD

**Issue by SorenBonde** [backdrop-contrib/paragraphs#41]
I am getting the following error when trying to translate a node which includes paragraphs:
`EntityMetadataWrapperException: Unknown data property [field_name]. in EntityStructureWrapper->getPropertyInfo() (line 335 of /modules/entity_plus/includes/entity_plus.wrapper.inc).`

I have installed the following modules: 
- Entity Plus 1.x-1.0.3
- Paragraphs 1.x-1.0.1
- Replicate 1.x-1.2
- Replicate Paragraphs 1.x-1.3

Backdrop version: 1.14.1

Hope someone out there might have a solution to this problem, since I really don't want to manually create all paragraphs on each node for each language.

**Comment by laryn** [comment]
@dBonde Can you test with the latest 1.x-1.x dev and let me know if it works for you?

**Comment by SorenBonde** [comment]
@laryn tanks for your reply. 
I am a bit uncertain to which module and which version you are referring.
Is it Paragraphs, Replicate, Replicate Paragraphs or Entity Plus?

**Comment by laryn** [comment]
Sorry, I made an assumption since this is in the paragraphs queue -- I was referring to paragraphs.

**Comment by SorenBonde** [comment]
No problem, I thought that was what you where referring to, just wanted to be sure. :-)
Just tested with paragraphs-1.x-1.0.1-beta and got the exact same error. :-(
Couldn't find any dev version, so assumed you where referring to the beta version.

**Comment by laryn** [comment]
@dBonde 
I'll try to recreate. I am using Paragraphs on a multilingual site and it's working, so I'll see what's different in my setup than in yours.

**Comment by laryn** [comment]
@dBonde Do you have any other modules installed or any other non-standard fields on that node?

I set up a test site with all of these modules (except Entity Plus), activated locale and content translation, added a language, added a test paragraph bundle, added a paragraphs field to a content type... and was able to create content in one language and then translate it (with the paragraph pre-populating) without an issue.

Then I activated Entity Plus and was able to do the same again with no issues.

What types of Paragraph bundles have you added on that node?

**Comment by SorenBonde** [comment]
@laryn thanks a lot for testing this. Could it be that I have nested paragraphs?

**Comment by SorenBonde** [comment]
@laryn just tried translating af node without nested paragraphs and it worked fine.
So it is the nested paragraphs that is causing the problem. :-/

**Comment by SorenBonde** [comment]
Just tried to uninstall the Entity Plus module and tried translating a node with nested paragraphs and got the following error:
`Error: Call to undefined function entity_metadata_wrapper() i replicate_paragraphs_clone_items() (linje 54 af /usr/www/users/supertqf/dtl/modules/replicate_paragraphs/replicate_paragraphs.module).
`

So not really a paragraph issue but a Replicate Paragraph issue.
Created a new issue in the right issue queue, sorry for posting it in the wrong issue queue. :-(
https://github.com/backdrop-contrib/replicate_paragraphs/issues/1

**Comment by laryn** [comment]
@dBonde I'm the maintainer there as well so I'll try to find some time to troubleshoot. I was able to replicate with nested paragraphs.

**Comment by SorenBonde** [comment]
@laryn thanks :-)
