### ISSUE TITLE
Convert Paragraphs to CMI

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/paragraphs#46]
Do we need to more thoroughly convert Paragraphs to CMI? I see that there are database tables for `paragraphs_bundle`, `paragraphs_item`, etc. which may need to be converted to CMI [in a similar way to what Nodes have](https://github.com/backdrop/backdrop-issues/issues/171) (e.g. `node.type.page.json`). (Related: [convert node types to CMI](https://github.com/backdrop/backdrop/blob/1.x/core/modules/node/node.install#L440-L489); [remove table and update schema](https://github.com/backdrop/backdrop/pull/986/files))

I've begun moving Paragraphs terminology from `bundle` to `type`, so we could end up with a config file for paragraphs like `paragraphs.type.pullquote.json`.

**Comment by robertgarrigos** [comment]
Just created a PR (https://github.com/backdrop-contrib/paragraphs/pull/66) for this.

**Comment by laryn** [comment]
This was marked as `2.0` but it is actually quite painless (thanks @robertgarrigos !) so I've merged it in to `1.x`
