### ISSUE TITLE
Paragraphs and Views

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/paragraphs#5]
I was having trouble trying to get Views working with Paragraphs and I think I figured it out but can't figure out how to upload an image to the wiki... so I'm adding it here.

![paragraphs-views-backdropcms](https://user-images.githubusercontent.com/871421/43086230-7ce455a0-8e62-11e8-809b-640a28008f93.jpg)

**Comment by laryn** [comment]
Here's the Wiki page:

https://github.com/backdrop-contrib/paragraphs/wiki/Paragraphs-and-Views

**Comment by docwilmot** [comment]
Thx for that. I'm sure it will come in handy for someone.
