### ISSUE TITLE
Paragraph field `REMOVE` button is blue but op is destructive.

### ISSUE THREAD

**Issue by serundeputy** [backdrop-contrib/paragraphs#55]
I think the paragraphs field button to `REMOVE` and item should be red to indicate destructive op.

What it is:

![image](https://user-images.githubusercontent.com/6763671/77232549-073e6a80-6b78-11ea-86f5-0b878ff4f8a7.png)

What I want:

![image](https://user-images.githubusercontent.com/6763671/77232565-2210df00-6b78-11ea-9b33-8fe95317acf1.png)

----

PR: https://github.com/backdrop-contrib/paragraphs/pull/56

**Comment by serundeputy** [comment]
filed PR at https://github.com/backdrop-contrib/paragraphs/pull/56

**Comment by laryn** [comment]
Thanks @serundeputy I also added `danger` to the Confirm Deletion button.
