### ISSUE TITLE
Allow separate modal edit/delete/sort of Paragraph items

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/paragraphs#60]
I have been meaning to see if I could figure out how to allow editing of individual Paragraph items via contextual link rather than requiring the entire node to be loaded. (For example, if one item way down the page needs a minor tweak, it would be way simpler to be able to edit that one item rather than load the entire page, scroll down to find that paragraph with everything else around it, potentially have to expand that Paragraph item before being able to edit it...)

My idea included opening the edit window in a modal and refreshing the page when it was submitted, but that may not be necessary. It turns out there's [an issue](https://www.drupal.org/project/paragraphs/issues/2448677) (and [a patch](https://www.drupal.org/files/issues/paragraphs_support-separate-paragraph-item-editing_2448677-63.patch)) in the Drupal queue that aims for very similar functionality (minus the modal). And follow up issues could be the ability to [delete/insert Paragraphs in this way](https://www.drupal.org/project/paragraphs/issues/2715833), and maybe even reorder (e.g. Move up, Move down).

I've tried to implement that first patch in the [issue-60](https://github.com/backdrop-contrib/paragraphs/tree/issue-60) branch.

~~The main issue I'm finding seems to be that host entity details aren't being tracked. This causes the access check to fail and the save to fail (Unable to save a paragraph without a valid reference to a host entity.).~~

~~I've temporarily adjusted the access check to include a new permission rather than checking whether the user has access to update the host entity, and could override the save not to check the host entity as well (but then we'd lose Paragraph revisions on nodes when edited in this way).~~

**Comment by laryn** [comment]
This is the `$paragraphs_item` entity as loaded in `paragraphs_form_edit`:
![Screen Shot 2020-04-20 at 4 23 23 PM](https://user-images.githubusercontent.com/871421/79801627-0a1dae00-8324-11ea-9991-a5bcedd92c4c.jpg)

And here's what it looks like in Drupal 7:
![Screen Shot 2020-04-21 at 4 33 35 PM](https://user-images.githubusercontent.com/871421/79916253-09514e80-83ee-11ea-83cc-d132a5bfc784.jpg)

**Comment by laryn** [comment]
I've made some progress, I think. I would appreciate anyone with more code experience looking over the changes I'm attempting:

https://github.com/backdrop-contrib/paragraphs/tree/contextual_edit

Right now it seems to work for Nodes, and partially for Taxonomy Terms (ie. it allows edit and save but it duplicates the same Paragraph item every time you save it -- something's off on the delta somewhere). 

Comments or feedback welcome!

**Comment by laryn** [comment]
I think this is functional now. Anyone care to test and/or glance over the code for a quick review?
Tested with Paragraph fields on a node, a taxonomy term, and a user.

When you add the Paragraph field to an entity, this box needs to be checked in order for contextual links to be added:

> ![Screen Shot 2020-04-22 at 12 25 01 AM](https://user-images.githubusercontent.com/871421/79943874-b9937700-842f-11ea-81dd-ab6569e1e712.jpg)

**Comment by laryn** [comment]
Playing around with an alternate implementation that uses dropbutton instead of contextual link, so there are two separate branches related to this issue:

 - https://github.com/backdrop-contrib/paragraphs/tree/issue-60-dropbutton (Dropbuttons)
 - https://github.com/backdrop-contrib/paragraphs/tree/issue-60 (Contextual links)

**Comment by olafgrabienski** [comment]
I've started to play around with the Dropbutton branch, looks really good at first sight. I like this approach more than the Contextual links approach.

**Comment by olafgrabienski** [comment]
Editing a Paragraph using Dropbuttons, I've encountered a strange behavior:

Upon Edit of a Paragraph, the background color and the Account menu in the header section of the page change their appearance. Looks like the styles are coming from the admin theme. Not sure if it's intended but that's not my issue. The issue is that this appearance remains after saving the Paragraph. (When I reload the page, it changes back to the expected appearance.) See the screenshots below.

**(1) View the page**

![backdrop-paragraphs-1-view](https://user-images.githubusercontent.com/14188307/111637587-dc720b00-87f9-11eb-8d5f-95b749ec7f85.png)

**(2) Edit paragraph**

![backdrop-paragraphs-2-edit](https://user-images.githubusercontent.com/14188307/111637594-de3bce80-87f9-11eb-81fa-d0442813db28.png)

**(3) Edited and saved**

![backdrop-paragraphs-3-edited](https://user-images.githubusercontent.com/14188307/111637599-ded46500-87f9-11eb-9b11-68606311567a.png)

**Comment by laryn** [comment]
@olafgrabienski I'm going to move that into a separate issue related to core bugs: https://github.com/backdrop-contrib/paragraphs/issues/81

**Comment by laryn** [comment]
I've merged this in for the next alpha pre-release. Open new issues around this feature as you test!

**Comment by laryn** [comment]
After two alphas and a beta, I think we're at a point where we can do a first formal release that includes this functionality (using dropbutton instead of contextual links). Big thanks to @olafgrabienski for helping me test and to those that did the heavy lifting (using contextual links) in the Drupal 7 thread with patches, testing and feedback, including: @ModulesUnraveled, @darthsteven, jonathanshaw, @iaminawe, Grayle, Nchase, @stevetweeddale, RAFA3L, delacosta456, @PascalMortier, 8bitplateau, Ludo.R, @StryKaizer, jeroen.b, @mirodietiker, @anotherjames, @Nebel54, @martijnhoutman, @vollepeer, @amoebanath, @rgpublic, vaccinemedia, screon, loominade, Alexandre360, reekris, and georgiana-albu.
