### ISSUE TITLE
Leftover entity_revision_load() needs updating

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/paragraphs#71]
There's still a call to `entity_revision_load()` in `ParagraphsItemEntity.inc` that needs updating to `entity_plus_revision_load()`...

**Comment by ghost** [comment]
Made a PR: https://github.com/backdrop-contrib/paragraphs/pull/72

**Comment by laryn** [comment]
Thanks @BWPanda -- it looks like that snuck back in when I merged upstream changes. My bad!
