### ISSUE TITLE
Two Label fields confusing

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/paragraphs#75]
![image](https://user-images.githubusercontent.com/2385329/100556713-538d9d00-32f8-11eb-9973-d1350b47d296.png)

I think one should be renamed Administrative Label, or something like that. Same as other places in Backdrop...

**Comment by laryn** [comment]
This came in with https://www.drupal.org/project/paragraphs/issues/2568601

I've made a few adjustments to sync up with Backdrop's interface:

- aligned the first field/description with the Content type form (e.g. "Name")
- aligned the label with the language of the new block "Admin label" field
- adjusted "bundle" to "Paragraph type" to stay consistent in the UI
- adjusted the Paragraphs admin screen to actually use the new theme function that Drupal issue brought in (for displaying "Admin label" and "Description" as it indicates it will).

https://github.com/backdrop-contrib/paragraphs/commit/0a530821a5ddba6624ea08949e42576339d5daed
