### ISSUE TITLE
Add links to Paragraphs-related modules in README

### ISSUE THREAD

**Issue by alanmels** [backdrop-contrib/paragraphs#76]
Readme file mentions accordion, but no real example is shown. So I've gone ahead and ported [Paragraphs jQuery UI Accordion](https://github.com/backdrop-contrib/paragraphs_jquery_ui_accordion). Tested with the Paragraphs module, works just as expected. Please reference Paragraphs jQuery UI Accordion in the Readme file

**Comment by laryn** [comment]
Thanks @alanmels !
