### ISSUE TITLE
Update issue: Undefined variable/Invalid argument

### ISSUE THREAD

**Issue by djzwerg** [backdrop-contrib/paragraphs#77]
After updating from 1.0 to 1.1 the following error messages were logged:

> 
> Notice: Undefined variable: bundles in paragraphs_update_1001() (line 229 of /mypathtobackdrop/modules/paragraphs/paragraphs.install).

> Warning: Invalid argument supplied for foreach() in paragraphs_update_1001() (line 229 of /mypathtobackdrop/modules/paragraphs/paragraphs.install).

**Comment by laryn** [comment]
@djzwerg Did/do you have any paragraph bundles defined on the site that you were upgrading the module on?

**Comment by djzwerg** [comment]
@laryn not yet

**Comment by laryn** [comment]
Okay, I think it is just warning that there were no bundles to upgrade. I'll leave this open for now -- we might as well check to make sure there is a result before trying to run the upgrade!

I don't think this will cause any problems for you since you can no paragraph types defined.
