### ISSUE TITLE
CKEditor not working in long text fields

### ISSUE THREAD

**Issue by djzwerg** [backdrop-contrib/paragraphs#84]
I'm not sure whether this is a bug - when I'm using the long text field it doesn't show the CKEditor (the long text field with summary works):

![grafik](https://user-images.githubusercontent.com/49948628/120167543-287bfb80-c1fe-11eb-9237-1f5c66591d08.png)

**Comment by laryn** [comment]
Can you provide steps to reproduce this? I haven't noticed it in my usage.

**Comment by djzwerg** [comment]
Sorry @laryn for the delay. After a few tests it works as designed. I don't know what causes my issue but not it's working on different sites.
