### ISSUE TITLE
How to style fields within paragraph bundles?

### ISSUE THREAD

**Issue by djzwerg** [backdrop-contrib/paragraphs#85]
I want to style the output of [field_title] to a heading (h2) so I tried this:

- Create file paragraphs-item-text_formatiert.tpl.php from paraphs/module directory and put it into [mytheme]/templates folder
- Inside the php file I tried

```
<div class="<?php print implode(' ', $classes); ?>"<?php print backdrop_attributes($attributes); ?>>
  <div class="content"<?php print backdrop_attributes($content_attributes); ?>>
    <h2><?php print render($content['field_ueberschrift']); ?></h2>
	<?php print render($content['field_inhalt']); ?>
  </div>
</div>
```
but it doesn't work. Maybe it is a duplicate of https://github.com/backdrop-contrib/paragraphs/issues/37?

**Comment by djzwerg** [comment]
Oh just my fault. I missed the second "-" in the filename (paragraphs-item**--**text_formatiert.tpl.php)

**Comment by laryn** [comment]
@djzwerg Glad you got it sorted. You can also use Field Wrappers for a non-code solution.
